### ISSUE TITLE
Rota2-020-Dudas sobre el proyecto

### ISSUE THREAD

**Issue by alegestor** [Decide-Part-Rota/decide-part-rota-2#21]
Contexto: Me he incorporado algo tarde al proyecto.

Enunciado de la pregunta: Dudas generales sobre la programación que se va a usar y en particular sobre cómo se tiene que elaborar la issue que tengo asignada sobre la mejora de interfaz de autenticación.

**Comment by Icaro212** [comment]
Buenas,

Estamos usando react en el proyecto y en concreto para tu tarea en particular deberías de familiarizarte con él. La única especificación así un poco más rara que te conviene saber es que no hemos hecho un wrapper de react con el proyecto sino que estamos importando las librerías en tiempo de ejecución y buildeando mediante javascript.

Un saludo
