### ISSUE TITLE
Rota2-014-Plantilla Incidencias

### ISSUE THREAD

**Issue by alegestor** [Decide-Part-Rota/decide-part-rota-2#5]
Descripción: Crear Plantilla para las incidencias utilizarla de manera homogénea  a lo largo del desarrollo del proyecto.

Módulo al que afecta: Cabina

Cambios a Introducir: Crear la propio plantilla en si

**Comment by Icaro212** [comment]
Se ha creado la siguiente plantilla

Plantilla de las Issues

Titulo 
	[RotaX-YYY-Funcionalidad]
	[RotaX-YYY]==>(Id)
	Siendo X el numero del grupo al que pertenece la Issue, YYY es un número individual asignado para la issue y "Funcionalidad" el titulo de la Issue en si el cual debe ser descriptivo

Labels Tipo
	-Bug: Para reportar algún fallo dentro de la aplicación
	-Question: Para preguntar por alguan dudad del funcionamiento de alguna funcionalidad
	-Enhancement: Para solictar el desarrollo de una nueva funcionalidad.

Labels Prioridad
	-Urgent: Realizar la tarea lo más rápido posible dentro de un margen de 24 horas  
	-Medium: Realizar la tarea dentro de un margen de 3 días
	-Low: Realizar la tarea dentro de un margen 5 días.

Descripción según el tipo de Label
	-Bug
		-Información sobre el entorno de la configuración 
		-Cual es el error?
		-Cuales son los pasos para replicar dicho error?
 		-Posibles soluciones aplicar (opcional)
	-Question
		-Contexto de la pregunta
		-Enunciado de la pregunta
	-Enhancement
		-Descripción de la nueva funcionalidad
		-Módulo a los que afecta
		-Indicación de los cambios a introducir en los otros modulos
