### ISSUE TITLE
Rota2-015-Patrón de para hacer commits.

### ISSUE THREAD

**Issue by alegestor** [Decide-Part-Rota/decide-part-rota-2#8]
Descripción: Elegir un patrón a la hora de hacer commits y usarla de manera homogénea durante el desarrollo del proyecto.

Modulo al que afecta: Cabina

Cambios a Introducir: Elegir el patrón para realizar los commits

**Comment by Icaro212** [comment]
Se ha definido la siguiente plantilla para las commits

<type>: <description>

[optional body]

(Important this is template to be erase before you do a commit. DO NOT FORGET TO ERASE ALL THE INFO IN THIS TEMPLATE!)
Types of <type>:
	fix: this commit patches a bug in your codebase
	feat: this commit introduces a new feature to the codebase
	test: this commit introduces new test for a funtionality in the codebase

<description> An usuful an short summary  of the work done in the commit
<body> A more in depth description of the new functionality (optional)
